packages:
  - 'apps/game-chat'
  # all packages in direct subdirs of packages/
  - 'packages/fe-game'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # exclude a Proof of Concept package, not part of the final project
  - '!packages/poc'
