packages:
  - 'apps/game-chat'
  - 'apps/game-server'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # exclude a Proof of Concept package, not part of the final project
  - '!packages/poc'
